spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: "vendo.marketplace.real@gmail.com"
    password: "qivlskruhrwqizxy"
    from: "vendo.marketplace.real@gmail.com"
    properties:
      mail:
        transport:
          protocol: smtp
        smtp:
          auth: true
          starttls:
            enable: true