spring:
  data:
    redis:
      port: 6379
      host: localhost

kafka:
  port: 9092
  host: localhost

services:
  api-gateway:
    port: 8030
    host: localhost
  registry-service:
    port: 8020
    host: localhost
