server:
  port: ${server.ports.user-service}

spring:
  data:
    mongodb:
      username: root
      password: secret
      database: mydatabase
      host: ${server.host}
      port: 27017

security:
  jwt:
    secret-key: rIIdcRkPQXdNGjV0ct2wFFl3onEWbqOOS2FtZWvpl5V85hKmnyU953q_EOmUr6px
    access-expiration-time: 30000
    refresh-expiration-time: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.host}:${server.ports.registry-service}/eureka/

management:
  tracing:
    sampling:
      probability: 1.0