server:
  port: ${server.ports.user-service}

spring:
  data:
    mongodb:
      uri: mongodb://root:password@${server.host}:27017/mydatabase?authSource=admin

security:
  jwt:
    secret-key: rIIdcRkPQXdNGjV0ct2wFFl3onEWbqOOS2FtZWvpl5V85hKmnyU953q_EOmUr6px
    access-expiration-time: 30000
    refresh-expiration-time: 60000

eureka:
  client:
    serviceUrl:
      defaultZone: http://${server.host}:${server.ports.registry-service}/eureka/

management:
  tracing:
    sampling:
      probability: 1.0